### PR TITLE
Fix syntax errors in config.php template

### PR DESCRIPTION
**Pull request by CthulhuDen**

### CODE REVIEW

**Comment by HeahDude** [comment]
Thanks @CthulhuDen.

This should target 4.0 branch.

You can either rebase and change the target thanks to GitHub's new feature by clicking on "edit" on the title of the PR, or we can handle it on merge.

**Comment by HeahDude** [comment]
👍

**Comment by CthulhuDen** [comment]
@HeahDude I tried to do that, but it seems it now tries to merge master into 4.0. Perhaps I should just open another PR.

**Comment by HeahDude** [comment]
@CthulhuDen If you don't know how to rebase on 4.0, just reset the target branch to master, we will handle it on merge. Thank you.

**Comment by CthulhuDen** [comment]
@HeahDude I just checked, this bug is not in 4.0 branch, it was introduced during merge.

**Comment by HeahDude** [comment]
Nice, thanks again :)

**Comment by waplet** [comment]
Any ideas when this will be applied?

**Comment by fabpot** [comment]
Thank you @CthulhuDen.

**Pull request merged**
