### PR TITLE
Remove everything related to the deprecated AcmeDemoBundle

### PR DESCRIPTION
**Pull request by javiereguiluz**
### The context

`AcmeDemoBundle` is deprecated because of the new [SymfonyDemoApplication](https://github.com/symfony/symfony-demo). This bundle should no longer appear when creating a project with the Symfony Standard Edition (no matter if you use the Symfony Installer or the Composer installation).

### The problem

In the past I tried to remove this bundle (see #198). However, when you install Symfony you still get this annoying bundle, so you cannot get a fresh clean Symfony installation.

### The solution

I propose to remove the AcmeDemoBundle for once and for all by removing all its files.

Please note that in the `Composer/ScriptHandler.php` there are two methods called `installAcmeDemoBundle()` and `patchAcmeDemoBundleConfiguration()` which I've emptied but left for BC reasons. @stof do you think we could removed these two methods entirely? Thanks.

### CODE REVIEW

**Comment by fabpot** [comment]
I don't think we need to keep BC in the ScriptHandler script.

**Comment by fabpot** [comment]
One way to keep BC would be to bump version to 4.0 for the bundle and update the symfony SE to use the new version for all new versions (including 2.3?).

**Comment by javiereguiluz** [comment]
It's great to hear that. I've created two separate pull requests to remove the AcmeDemoBundle from Symfony Standard too:

  * 2.3: https://github.com/symfony/symfony-standard/pull/818
  * 2.6+: https://github.com/symfony/symfony-standard/pull/819

**Comment by stof** [comment]
If we remove the methods, we indeed need to bump the major version as it is a BC break for anyone using it in their composer.json. but it is fine IMO

**Comment by Pierstoval** [comment]
Is it possible to simply throw a "deprecated" error in the composer script that tells the user to remove the methods in his `composer.json` file?

**Comment by stof** [comment]
@Pierstoval this is a bad idea. Composer turns all PHP errors into exceptions, including the E_USER_DEPRECATED ones, meaning that it would make the composer installation fail if you trigger it in the script handler (and if you trigger it silenced, it will never be reported as the special error handler of Symfony logging all deprecations even silenced is not registered in Composer runs)

**Comment by Pierstoval** [comment]
So what is the best solution then? Show the message simply in the output?

**Comment by stof** [comment]
Well, in 3.x of the bundle, the handler should continue to work (for BC reasons). But we could indeed add a message in the output saying it is deprecated (not sure it is worth it as I'm not sure people will read it).
and in 4.0, we should just remove the methods entirely IMO and document the change in the upgrade instructions (it is an easy upgrade)

**Comment by Tobion** [comment]
:+1: for removing in 4.0. @javiereguiluz so you need to change the branch alias in composer.json

**Comment by fabpot** [comment]
I've bumped the version of the master branch to 4.0.

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
