### PR TITLE
Remove the web configurator

### PR DESCRIPTION
**Pull request by javiereguiluz**
I propose to remove the web configurator. Some arguments in favor of doing it:

  * It does two totally different things: check technical requirements and update the parameters file.
  * If we remove it, it's very easy to maintain the useful requirements checker (we already did this in the Symfony Demo application; see https://github.com/symfony/symfony-demo/pull/81)
  * When it was created, it was truly useful. Nowadays, its usefulness is unclear.
  * It's incredibly overengineered (again, because it was created a very long time ago).
  * If we remove it, we'll have 25 less files to manage and more than 1,000 less lines of code.

### CODE REVIEW

**Comment by stof** [comment]
Another argument: in many setups, it is unusable as it cannot replace the config file itself (not writable by the webserver) and many people will not read the message telling them that the file has been saved in the cache folder and that they need to move it.

So a big :+1: from me

**Comment by fabpot** [comment]
I suppose there are some links to the configurator that also need to be removed.

**Comment by stof** [comment]
Links to the configurator where in the AcmeDemoBundle homepage IIRC. I'm not sure we still have one (or maybe just in the requirement checker script maybe, to be checked)

**Comment by fabpot** [comment]
Do we need to bump the version to 5.0?

**Comment by stof** [comment]
following semver, we should

**Comment by stof** [comment]
and this is a BC break for people importing the configurator routing in their routing files, so we should indeed bump the major version to avoid breaking existing projects

**Comment by fabpot** [comment]
@javiereguiluz Can you bump the version in Composer?

**Comment by javiereguiluz** [comment]
Rebased and bumped to 5.0.

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Comment by xabbuh** [comment]
@fabpot I think you need to create a new branch for `4.0-dev`.

**Comment by stof** [comment]
@xabbuh why ? We don't need it if we don't make any change based on 4.0 now. IMO, it is perfectly fine to say that people wanting new features should switch to the 5.0 version

**Comment by mayeco** [comment]
:+1:

**Comment by xabbuh** [comment]
Fair enough, I mistakenly assumed that there were more changes which justified to continue to maintain a dedicated 4.0 branch.

**Pull request closed without merging**
