### PR TITLE
[Fix] Notice: A non well formed numeric value encountered

### PR DESCRIPTION
**Pull request by anddezr**
realpath_cache_size can be with or without unit. 
Remove last character ($unit) from string $size if not all characters in $size are numerical.

### CODE REVIEW

**Comment by HeahDude** [comment]
LGTM 👍

**Comment by fabpot** [comment]
Thank you @anddezr.

**Comment by Fabr9193** [comment]
Hello ! Still having this issue when launching the clearCache script when using composer install :/

**Comment by Fabr9193** [comment]
even though i have tried to add a php.ini and change my own value

when i type  php -i |  grep -i "realpath" i get :

realpath_cache_size => 4096k => 4096k

**Pull request closed without merging**
