### PR TITLE
Resolve PHP 5.2 namespace incompatibility

### PR DESCRIPTION
**Pull request by freak**
Removed incompatibile global namespace prefix "\" from ReflectionClass and ReflectionException

### CODE REVIEW

**Comment by apfelbox** [comment]
You shouldn't use this bundle with PHP < 5.3.9.

The `composer.json` states the same:

```
"require": {
    "php": ">=5.3.9",
    ...
}
```

**Comment by lyrixx** [comment]
@apfelbox Anyway, this patch is valid ;)

**Comment by jvasseur** [comment]
@apfelbox The symfony requirements sould work on the lowest possible version of PHP to warn the user that his version is to old.

**Comment by fabpot** [comment]
Thank you @freak.

**Comment by apfelbox** [comment]
@jvasseur that is correct. My comment meant, that you can't install the package using composer on PHP 5.2, so you can't possibly come into that situation that the file won't work when installing it via composer.

If you don't install it via composer (like using symfony installer or just downloading a zip file) it is possible, of course.

(whether it makes sense to say on one hand "ok, this package is PHP 5.3+" and on the other hand "yeah, the code is 5.2, too" or whether one should probably separate it – that is another debate)

**Pull request closed without merging**
