### PR TITLE
Do not use inline yml for the parameters.yml

### PR DESCRIPTION
**Pull request by Xosofox**
Expand the yaml to be mor euser friendly

### CODE REVIEW

**Comment by xabbuh** [comment]
So this addresses symfony/symfony#14015?

**Comment by Xosofox** [comment]
Exactly, I stumbled upon it yesterday and thought to fix it. However, I see there are discussions going on to remove the config completely, so I did not bother fixing the (other people's) coding standards issues ;-)

**Comment by fabpot** [comment]
Merging it in the 3.0 branch.

**Comment by fabpot** [comment]
Thank you @Xosofox.

**Pull request closed without merging**
